export interface President {
    id?: number,
    image?: string,
    massar?: string,
    nom?: string,
    prenom?: string,
    genre?: string,
    dateNaissance?: string,
    pere?: {
        nomPere?: string,
        prenomPere?: string,
        proffessionPere?: string,
        niveauPere?: string,
    },
    mere?: {
        nomMere?: string,
        prenomMere?: string,
        proffessionMere?: string,
        niveauMere?: string,
    },
    nbFreres?: string,
    triFreres?: string,
    adresse?: string,
    distance?: string,
    telephone?: string,
    gerant?: string,
    orphelin?: string[],
    divorce?: string,
    zone?: string,
    typeResidence?: string,
    chambre?: string,
    primaire?: string[],
    besoins?: string[],
    favorites?: string[],
    santes?: {
        key?: string,
        value?: string,
        isSante?: boolean,
    }[],
    malades?: string,
    remarques?: string,
}